In [1]:
from numpy.random import randn
import numpy as np

In [2]:
# 그래프를 바로 보기 위한 명령어
%matplotlib inline

# The NumPy ndarray: a multidimensional array object
>  
다차원 배열 객체

In [3]:
data = randn(2, 3)
data

array([[-1.46224188,  0.51431012,  1.10015793],
       [-1.44800424, -0.39629766, -1.55052189]])

In [4]:
data*10

array([[-14.62241879,   5.14310124,  11.00157925],
       [-14.48004244,  -3.96297664, -15.5052189 ]])

In [5]:
data.shape # array 구조 알고 싶을 때

(2, 3)

In [6]:
data.dtype

dtype('float64')

In [7]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1) # array로 만들면 vectorization 처럼 연산이 가능함
arr1 # 데이터 타입이 다를경우 array를 만들면 동일화

array([6. , 7.5, 8. , 0. , 1. ])

In [8]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
arr2.ndim

2

In [10]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [13]:
np.empty((2,3,4)) # 뒤에서 부터 해석

array([[[6.23042070e-307, 3.56043053e-307, 1.37961641e-306,
         1.33508845e-306],
        [1.33511969e-306, 6.23037996e-307, 6.23053954e-307,
         9.34609790e-307],
        [8.45593934e-307, 9.34600963e-307, 7.56599128e-307,
         1.37961913e-306]],

       [[8.01097889e-307, 8.45593934e-307, 8.90104239e-307,
         6.89805151e-307],
        [7.56592338e-307, 6.89807188e-307, 6.89805151e-307,
         1.78020169e-306],
        [8.45559303e-307, 1.06811422e-306, 1.05694828e-307,
         2.22522596e-306]]])

[Tip] np.empty<br> - 빈 껍데기 만들어줌
np.empty는 0으로 초기화된 배열을 반환하지 않는다.<br>
대부분 empty는 0이 아닌 값으로 채워진 배열을 반환한다.

In [14]:
np.arange(15) # array range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [15]:
np.array(range(15))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [19]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(float) # 파이썬에서는 str(data) 하면 됬음

array([ 1.25, -9.6 , 42.  ])

In [20]:
int_array = np.arange(10)
int_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
calibers

array([0.22 , 0.27 , 0.357, 0.38 , 0.44 , 0.5  ])

In [23]:
int_array.astype(calibers.dtype) # 해당 데이터와 데이터 타입을 맞추고 싶을 때

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [24]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [25]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [26]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [27]:
arr = np.arange(10)
arr
# arr[5]
# arr[5:8]
# arr[5:8] = 12

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
arr[5]

5

In [29]:
arr[5:8]

array([5, 6, 7])

In [30]:
arr[5:8] = 12

In [31]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [32]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [33]:
arr_slice[1] = 12345

In [34]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [35]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [37]:
data = randn(7, 4)
data

array([[-0.26451947,  0.04256641,  0.89243503,  0.32834412],
       [-0.94478681,  0.01941979, -0.77326136,  0.24834627],
       [ 0.44818397, -0.49602962,  0.81567214, -0.31949193],
       [ 0.8176281 ,  0.1132429 ,  0.31658471,  0.33844217],
       [-0.55471999, -0.50467327,  0.06532998, -2.19404858],
       [-0.9039916 , -0.96233262, -0.84159739,  1.01917037],
       [-0.66320811,  0.06837309,  0.88067817,  0.95651689]])

In [38]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [39]:
data[names == 'Bob']

array([[-0.26451947,  0.04256641,  0.89243503,  0.32834412],
       [ 0.8176281 ,  0.1132429 ,  0.31658471,  0.33844217]])

In [40]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [41]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [42]:
data[data < 0]

array([-0.26451947, -0.94478681, -0.77326136, -0.49602962, -0.31949193,
       -0.55471999, -0.50467327, -2.19404858, -0.9039916 , -0.96233262,
       -0.84159739, -0.66320811])

In [43]:
data[names != 'Joe'] = 7
data

array([[ 7.        ,  7.        ,  7.        ,  7.        ],
       [-0.94478681,  0.01941979, -0.77326136,  0.24834627],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [-0.9039916 , -0.96233262, -0.84159739,  1.01917037],
       [-0.66320811,  0.06837309,  0.88067817,  0.95651689]])

In [44]:
data

array([[ 7.        ,  7.        ,  7.        ,  7.        ],
       [-0.94478681,  0.01941979, -0.77326136,  0.24834627],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [-0.9039916 , -0.96233262, -0.84159739,  1.01917037],
       [-0.66320811,  0.06837309,  0.88067817,  0.95651689]])

In [45]:
data[~(names == 'Bob')]

array([[-0.94478681,  0.01941979, -0.77326136,  0.24834627],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [-0.9039916 , -0.96233262, -0.84159739,  1.01917037],
       [-0.66320811,  0.06837309,  0.88067817,  0.95651689]])

In [46]:
data[names != 'Bob']

array([[-0.94478681,  0.01941979, -0.77326136,  0.24834627],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [-0.9039916 , -0.96233262, -0.84159739,  1.01917037],
       [-0.66320811,  0.06837309,  0.88067817,  0.95651689]])

In [47]:
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [48]:
data[mask]

array([[7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.]])

In [49]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [50]:
arr = np.empty((8, 4))

In [51]:
arr

array([[2.05833592e-312, 2.05833592e-312, 6.79038653e-313,
        6.79038653e-313],
       [1.93101617e-312, 9.33678148e-313, 1.06099790e-312,
        6.79038653e-313],
       [9.33678148e-313, 1.10343781e-312, 9.33678148e-313,
        1.93101617e-312],
       [9.33678148e-313, 1.14587773e-312, 6.79038653e-313,
        9.33678148e-313],
       [1.18831764e-312, 1.97345609e-312, 2.05833592e-312,
        2.41907520e-312],
       [6.79038653e-313, 6.79038653e-313, 2.37663529e-312,
        2.05833592e-312],
       [2.41907520e-312, 2.56761491e-312, 2.12199579e-312,
        2.46151512e-312],
       [1.06099790e-312, 2.12199579e-313, 2.41907520e-312,
        1.06099790e-312]])

In [53]:
for i in range(8):
    arr[i] = i

In [54]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [55]:
arr[4]

array([4., 4., 4., 4.])

In [56]:
arr[[4]]

array([[4., 4., 4., 4.]])

In [57]:
arr[[4,2]]

array([[4., 4., 4., 4.],
       [2., 2., 2., 2.]])

In [58]:
arr = np.arange(32)

In [65]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [67]:
arr= arr.reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [71]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [72]:
arr[np.ix_([1, 5, 7, 2], [0, 3, 1, 2])]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [73]:
arr[np.ix_([1, 5, 7, 2], [0, 3, 1, 2])]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [76]:
arr = np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [77]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [81]:
arr = np.random.randn(6, 3)
arr

array([[ 0.95741234, -0.25319076, -2.66993576],
       [-0.92959771, -0.18323943,  0.47789124],
       [ 1.28138014,  0.73675255, -0.90906398],
       [-0.02990208, -1.19420351,  0.49105715],
       [ 0.93151757, -1.14737046, -0.33307694],
       [-0.42298373, -0.60631561,  0.92980965]])

In [82]:
np.dot(arr.T, arr) # dot은 행렬식 곱

array([[ 4.47025969,  0.09536614, -4.88357757],
       [ 0.09536614,  3.75068621, -0.84933829],
       [-4.88357757, -0.84933829,  9.39995765]])

In [83]:
?arr.transpose

In [ ]:
arr.swapaxes(1, 2) # axis0 과 axis2를 바꿈